tech_talent_blog/config/routes.rb
Rails.application.routes.draw do

  resources :blog_posts

  root 'blog_posts#index'

end

tech_talent_blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tech_talent_blog/app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, :blog_entry, presence: true
  validates :title, uniqueness: true, length: {maximum: 140}
end

tech_talent_blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tech_talent_blog/app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  
  def index
    @blog_posts = BlogPost.all #Collection of all the instances of BlogPost in our database
  end

  def show
  end

  def edit
  end

  def new
    @blog_post = BlogPost.new #Creating a new instance of BlogPost (remember initialize from ruby classes)
  end

  def create
    @blog_post = BlogPost.new(blog_post_params) #method we will set up in a second here. This method will help us allow all of the BlogPost attributes
    respond_to do |format|
      if @blog_post.save #Method from the blogPost class
        	format.html { redirect_to blog_post_url(@blog_post), notice: "Blog Post
    		was created successfully."} #route when BlogPost successfully saved to database
      else
        format.html {render :new} #render to new blog post page when blog post can't be saved to database
      end
    end
  end

  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params) #blog_post.update is from the BlogPost class
        format.html { redirect_to blog_post_url(@blog_post), notice: "Blog post was updated successfully"}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @blog_post.destroy #Method from the BlogPost class
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: "Your Blog Post was DESTROYEDDDDDDDDDD!!!!!!!!!"}
      # Route to when a blog post is destroyed. I could have set instead also root_url as BlogPost index view is also the root page
    end
  end

  private

    def set_blog_post
        @blog_post = BlogPost.find(params[:id])
    end
    def blog_post_params
      params.require(:blog_post).permit(:title, :blog_entry, :author)
    end

end

tech_talent_blog/app/helpers/application_helper.rb
module ApplicationHelper
end

tech_talent_blog/app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

tech_talent_blog/app/views/blog_posts/_form.html.erb
<%= form_with(model: @blog_post, local: true) do |form| %>
<% if @blog_post.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@blog_posts.errors.count, "error") %>
      prohibited this blog_pst from being saved:
    </h2>
    <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form-group">
  <%= form.text_field :title, class: "form-control", placeholder: "Blog Title...." %>
</div>
<div class="form-group">
  <%= form.text_field :author, class: "form-control", placeholder: "Your Name Here.." %>
</div>
<div class="form-group">
  <%= form.text_area :blog_entry, class: "form-control", rows: 12, placeholder: "Tell us Something" %>
</div>
<div class="actions">
  <%= form.submit "Post", class: "btn btn-primary" %>
</div>
<% end %>

tech_talent_blog/app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<br>

<%= link_to "Back", blog_post_path(@blog_post), class: "btn btn-info" %>

<%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default"%>

tech_talent_blog/app/views/blog_posts/index.html.erb
<h1>Current Blog Posts</h1>

<div class="row">
  <% @blog_posts.each do |blog_post| %>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= blog_post.title %>
        </div>
        <div class="panel-body">
          by
          <%= blog_post.author %><br>
          <p><%= blog_post.blog_entry %></p>
        </div>
        <div class="panel-footer">
          <%= link_to "Show", blog_post, class: "btn btn-info" %>
          <%= link_to "Edit", edit_blog_post_path(blog_post), class: "btn btn-warning" %>
          <%= link_to "Destroy", blog_post_path(blog_post), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= link_to "New Blog Post", new_blog_post_path, class: "btn btn-success" %>

tech_talent_blog/app/views/blog_posts/new.html.erb
<h1>Create a New Blog Post</h1>

<%= render 'form' %>

<br>

<%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default" %>

tech_talent_blog/app/views/blog_posts/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <%= @blog_post.title %>
  </div>
  <div class="panel-body">
    <p><%= @blog_post.author %></p>
    <p><%= @blog_post.blog_entry %></p>
  </div>
  <div class="panel-footer">
    <%= link_to "Edit", edit_blog_post_path(@blog_post), class: "btn btn- warning" %>
    <%= link_to "All Blog Posts", blog_posts_path, class: "btn btn-default" %>
  </div>
</div>

tech_talent_blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <%= yield %>


  </body>
</html>